project_id = "dymdchhxabwaxownoxtz"

[functions.pagarme-webhook]
verify_jwt = false

[functions.pagarme-create-link]
verify_jwt = false

[functions.get-customer-data]
verify_jwt = false

[functions.update-customer-domain]
verify_jwt = false

[functions.create-aluno-empresa]
verify_jwt = false

[functions.create-professor-user]
verify_jwt = false

[functions.create-escola-user]
verify_jwt = false
